files:
- generatedChecksum: 7FEE6F3F6F77EFB96604C4D87733DF92
  logicalPath: config\sam_v71_xult\bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7FEE6F3F6F77EFB96604C4D87733DF92
- generatedChecksum: 5DE3DBB3771EAD43D4566BC108191AB0
  logicalPath: config\sam_v71_xult
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5DE3DBB3771EAD43D4566BC108191AB0
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 849F55FE2A4A782252022BCD392A32F0
  logicalPath: config\sam_v71_xult\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 849F55FE2A4A782252022BCD392A32F0
- generatedChecksum: 79F1E7691AFEECE298BB94C2E49B1570
  logicalPath: config\sam_v71_xult\peripheral\efc
  name: plib_efc.c
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 79F1E7691AFEECE298BB94C2E49B1570
- generatedChecksum: 3BE167DA76FAF627FF9F2577A86E3154
  logicalPath: config\sam_v71_xult\peripheral\mcan
  name: plib_mcan1.c
  physicalPath: peripheral\mcan
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BE167DA76FAF627FF9F2577A86E3154
- generatedChecksum: 5FF5AB4E253C8975ACE2A20FB0A8E4E2
  logicalPath: config\sam_v71_xult\peripheral\mpu
  name: plib_mpu.c
  physicalPath: peripheral\mpu
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5FF5AB4E253C8975ACE2A20FB0A8E4E2
- generatedChecksum: 69D4749835DB4A22B51E2535A5357B83
  logicalPath: config\sam_v71_xult\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 69D4749835DB4A22B51E2535A5357B83
- generatedChecksum: 0B14BECDEC305F8E76A5BCC429951A8A
  logicalPath: config\sam_v71_xult\peripheral\pio
  name: plib_pio.c
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0B14BECDEC305F8E76A5BCC429951A8A
- generatedChecksum: 338F3F58BA5291CE0ADC155D2D1B0BA2
  logicalPath: config\sam_v71_xult
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 338F3F58BA5291CE0ADC155D2D1B0BA2
- generatedChecksum: 4F3D0E360C6385D2719AF5F2B55054F6
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: acc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4F3D0E360C6385D2719AF5F2B55054F6
- generatedChecksum: 65DDDADCEA8525CAAF1FE726D5DF3816
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: aes.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 65DDDADCEA8525CAAF1FE726D5DF3816
- generatedChecksum: E824205FBF0E93120E1B3D6F4255F118
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: afec.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E824205FBF0E93120E1B3D6F4255F118
- generatedChecksum: 82CC7871BF9167B7FCC303A5A164EE76
  logicalPath: packs\ATSAMV71Q21B_DFP
  name: atsamv71q21b.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 82CC7871BF9167B7FCC303A5A164EE76
- generatedChecksum: A1BC211CD91C925B2CF96A546E722D11
  logicalPath: config\sam_v71_xult\bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: A1BC211CD91C925B2CF96A546E722D11
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 92F055BEA60BEB62E5F93B7E560EF834
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: chipid.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 92F055BEA60BEB62E5F93B7E560EF834
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
- generatedChecksum: BA512C673524C311004D1950A5868766
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: dacc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BA512C673524C311004D1950A5868766
- generatedChecksum: A53610F19AEFE617589A0C0D8708EFDB
  logicalPath: config\sam_v71_xult
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A53610F19AEFE617589A0C0D8708EFDB
- generatedChecksum: FA27943D0D0BA1159156FBA17FD3B726
  logicalPath: config\sam_v71_xult
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA27943D0D0BA1159156FBA17FD3B726
- generatedChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
  logicalPath: config\sam_v71_xult
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
- generatedChecksum: CA018E095CCDDF70F831714213FB7EAC
  logicalPath: config\sam_v71_xult
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CA018E095CCDDF70F831714213FB7EAC
- generatedChecksum: BCC0E5F50D901787A705624AA8372E11
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: efc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BCC0E5F50D901787A705624AA8372E11
- generatedChecksum: 67033A8D2CA8875FBBBFF4BCDB2CECA7
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: gmac.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 67033A8D2CA8875FBBBFF4BCDB2CECA7
- generatedChecksum: 68BD813554AC86D9E67B9B4AE051F721
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: gpbr.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 68BD813554AC86D9E67B9B4AE051F721
- generatedChecksum: D6A13175CEEF7CC06255BD1BF1920C84
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: hsmci.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D6A13175CEEF7CC06255BD1BF1920C84
- generatedChecksum: DA5065C0943AF8C147556FF4A195BE8F
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: i2sc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DA5065C0943AF8C147556FF4A195BE8F
- generatedChecksum: 9B4015F7943E3C4060BBB0B7A2840914
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: icm.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B4015F7943E3C4060BBB0B7A2840914
- generatedChecksum: A3B5C73888BA770B71B0E4E776F2FD11
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: isi.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A3B5C73888BA770B71B0E4E776F2FD11
- generatedChecksum: 73CDD822C1718E0F93A71FDF019DF8BD
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: matrix.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 73CDD822C1718E0F93A71FDF019DF8BD
- generatedChecksum: 8105B3B3832E696CBD8A2BBDC59BDA27
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: mcan.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8105B3B3832E696CBD8A2BBDC59BDA27
- generatedChecksum: 62F0D473BB45AB284D108738F18867B3
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: mlb.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F0D473BB45AB284D108738F18867B3
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 20894420BCA8636ECA7030F8FD9EBE70
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: pio.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 20894420BCA8636ECA7030F8FD9EBE70
- generatedChecksum: BFDB10EBEF4DBDE66563BA7DD136A98F
  logicalPath: config\sam_v71_xult\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: BFDB10EBEF4DBDE66563BA7DD136A98F
- generatedChecksum: FB046CED42CA3B2AE1895C186571EF71
  logicalPath: config\sam_v71_xult\peripheral\efc
  name: plib_efc.h
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: HEADER
  userChecksum: FB046CED42CA3B2AE1895C186571EF71
- generatedChecksum: BAA9C0188E118BF376B22D7710F6BEBB
  logicalPath: config\sam_v71_xult\peripheral\mcan
  name: plib_mcan1.h
  physicalPath: peripheral\mcan
  security: NON_SECURE
  type: HEADER
  userChecksum: BAA9C0188E118BF376B22D7710F6BEBB
- generatedChecksum: 7B723EB9002B172891E025F48548FF3E
  logicalPath: config\sam_v71_xult\peripheral\mcan
  name: plib_mcan_common.h
  physicalPath: peripheral\mcan
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B723EB9002B172891E025F48548FF3E
- generatedChecksum: 6736D89FF27ACC5342105A1FCB2C5B13
  logicalPath: config\sam_v71_xult\peripheral\mpu
  name: plib_mpu.h
  physicalPath: peripheral\mpu
  security: NON_SECURE
  type: HEADER
  userChecksum: 6736D89FF27ACC5342105A1FCB2C5B13
- generatedChecksum: E13B3C3F2096A36698DDC9B5BDE2E776
  logicalPath: config\sam_v71_xult\peripheral\mpu
  name: plib_mpu_local.h
  physicalPath: peripheral\mpu
  security: NON_SECURE
  type: HEADER
  userChecksum: E13B3C3F2096A36698DDC9B5BDE2E776
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_v71_xult\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 421D7AEBE0C7204A032C98779B1730C0
  logicalPath: config\sam_v71_xult\peripheral\pio
  name: plib_pio.h
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 421D7AEBE0C7204A032C98779B1730C0
- generatedChecksum: A6E0A56BA103F51C4AA8347C9F00AC8A
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: pmc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A6E0A56BA103F51C4AA8347C9F00AC8A
- generatedChecksum: 20E28C8BD280F78797FCC350A5FC824D
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: pwm.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E28C8BD280F78797FCC350A5FC824D
- generatedChecksum: 1B70E73B1565B527911B1D8E16103C90
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: qspi.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1B70E73B1565B527911B1D8E16103C90
- generatedChecksum: AB7996D53710F9AAC1D40E01FEE331E6
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AB7996D53710F9AAC1D40E01FEE331E6
- generatedChecksum: D1AF4F07442106FE1FAC75BA5AE35A17
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: rswdt.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D1AF4F07442106FE1FAC75BA5AE35A17
- generatedChecksum: 20D9576F48EBBB33BD265C8AA3FF0F97
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 20D9576F48EBBB33BD265C8AA3FF0F97
- generatedChecksum: A1E0C9F6D3B0988BB4FD6BB1C70F9790
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: rtt.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A1E0C9F6D3B0988BB4FD6BB1C70F9790
- generatedChecksum: DFFF5143675BAEF27F26B7A36C3786E5
  logicalPath: packs\ATSAMV71Q21B_DFP\pio
  name: samv71q21b.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: DFFF5143675BAEF27F26B7A36C3786E5
- generatedChecksum: 66577716A29F7145E9547E02C2D7C246
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: sdramc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 66577716A29F7145E9547E02C2D7C246
- generatedChecksum: 3D90858C064E8090CACFC66BDF1F6F41
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: smc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D90858C064E8090CACFC66BDF1F6F41
- generatedChecksum: 9CD1CE6893A48F76498788E9DB4C8CAC
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: spi.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9CD1CE6893A48F76498788E9DB4C8CAC
- generatedChecksum: D59FB6E12CA182CBE28511A153698412
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: ssc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D59FB6E12CA182CBE28511A153698412
- generatedChecksum: 097E339507914EAE412A87AEE7DAB0DC
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 097E339507914EAE412A87AEE7DAB0DC
- generatedChecksum: C5553C61F0FA01B67CE81669CD4BA188
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C5553C61F0FA01B67CE81669CD4BA188
- generatedChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
  logicalPath: config\sam_v71_xult
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
- generatedChecksum: F1123AF4E42290FF5EF5F78ACA6948F1
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F1123AF4E42290FF5EF5F78ACA6948F1
- generatedChecksum: 102377CA922D564BAC58C2E181A4AB74
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: twihs.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 102377CA922D564BAC58C2E181A4AB74
- generatedChecksum: 7884F612B8975814CEE3E4003B75C6E4
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: uart.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7884F612B8975814CEE3E4003B75C6E4
- generatedChecksum: FEC87398C8BCFE8C1A280D6A00DC174E
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: usart.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FEC87398C8BCFE8C1A280D6A00DC174E
- generatedChecksum: BD472523BA90E6C7BA1609B0C38F69AA
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: usbhs.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BD472523BA90E6C7BA1609B0C38F69AA
- generatedChecksum: C0D0BD3744A579D6E9BA92DD29510617
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: utmi.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C0D0BD3744A579D6E9BA92DD29510617
- generatedChecksum: 6AFF7378493124345BEA3C50BF44A613
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6AFF7378493124345BEA3C50BF44A613
- generatedChecksum: 12FE8193A0EE9A5C47D25FECA80F3C00
  logicalPath: packs\ATSAMV71Q21B_DFP\component
  name: xdmac.h
  physicalPath: ..\..\packs\ATSAMV71Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 12FE8193A0EE9A5C47D25FECA80F3C00
- generatedChecksum: 88ECF3966E24669F94EE40B23B71C042
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 88ECF3966E24669F94EE40B23B71C042
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_v71_xult;../src/packs/ATSAMV71Q21B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32
  delimiter: ''
  key: place-data-into-section
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-startup-files
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_v71_xult;../src/packs/ATSAMV71Q21B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32Global
  delimiter: ''
  key: mdtcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mitcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mstacktcm
  security: NON_SECURE
  value: 'false'
sourcePaths: []
