package:
  format-version: "1.0.0"
  name: "bootloader_apps_can"
  version: "v3.3.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "v3.8.0"
