configName: pic32mk_mcm_curiosity_pro
folderName: pic32mk_mcm_curiosity_pro
format_version: v1.0
frameworkPath: C:\h3
processor: PIC32MK1024MCM100
projectName: pic32mk_mcm_curiosity_pro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MK-MC_DFP\1.11.151
