configName: pic32mk_gp_db
folderName: pic32mk_gp_db
format_version: v1.0
frameworkPath: C:\HF
processor: PIC32MK1024GPE100
projectName: pic32mk_gp_db
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MK-GP_DFP\1.6.144
