format_version: v1.0
type: UniqueComponent
attributes: {id: can_bootloader}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BTL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can_bootloader, value: '8192'}
      - type: User
        attributes: {value: '8192'}
  - type: Boolean
    attributes: {id: BTL_TRIGGER_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: BTL_TRIGGER_LEN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: String
    attributes: {id: MEM_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can_bootloader, value: NVMCTRL}
  - type: String
    attributes: {id: PERIPH_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can_bootloader, value: CAN}
  - type: String
    attributes: {id: PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can_bootloader, value: CAN1}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: btl_CAN_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: can1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: CAN1_CAN}
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvmctrl}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVMCTRL_MEMORY}
- type: ElementPosition
  attributes: {x: '30', y: '100', id: can_bootloader}
