configName: pic32mz_ef_curiosity
folderName: pic32mz_ef_curiosity
format_version: v1.0
frameworkPath: C:\Users\I76597\h3-BB
processor: PIC32MZ2048EFM144
projectName: pic32mz_ef_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-EF_DFP\1.3.58
