format_version: v1.0
configName: pic32mz_ef_curiosity
folderName: pic32mz_ef_curiosity
frameworkPath: C:\HF
processor: PIC32MZ2048EFM144
projectName: pic32mz_ef_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
