files:
- generatedChecksum: 6EFB39E1476B3D71B7AF4D76FAE4E30F
  logicalPath: config\sam_c21n_xpro\bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6EFB39E1476B3D71B7AF4D76FAE4E30F
- generatedChecksum: 13AD21F800D3402C865D949B3199D60A
  logicalPath: config\sam_c21n_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13AD21F800D3402C865D949B3199D60A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C0D814B42AA3EDF8D603E9C9474B1EB4
  logicalPath: config\sam_c21n_xpro\peripheral\can
  name: plib_can0.c
  physicalPath: peripheral\can
  security: NON_SECURE
  type: SOURCE
  userChecksum: C0D814B42AA3EDF8D603E9C9474B1EB4
- generatedChecksum: 7C77469FE7ECF5DB29A5B5BCD1A86AA8
  logicalPath: config\sam_c21n_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7C77469FE7ECF5DB29A5B5BCD1A86AA8
- generatedChecksum: 50542080584DC107D0C4FAC57DBE8DD4
  logicalPath: config\sam_c21n_xpro\peripheral\dsu
  name: plib_dsu.c
  physicalPath: peripheral\dsu
  security: NON_SECURE
  type: SOURCE
  userChecksum: 50542080584DC107D0C4FAC57DBE8DD4
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_c21n_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: D984FDA7A2C6E878F8BFA27EF0A658A6
  logicalPath: config\sam_c21n_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: D984FDA7A2C6E878F8BFA27EF0A658A6
- generatedChecksum: B63930B755D1356EE16C52AB9979947B
  logicalPath: config\sam_c21n_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: B63930B755D1356EE16C52AB9979947B
- generatedChecksum: A772B4B36285C94F1C31F2041A406E90
  logicalPath: config\sam_c21n_xpro\peripheral\pac
  name: plib_pac.c
  physicalPath: peripheral\pac
  security: NON_SECURE
  type: SOURCE
  userChecksum: A772B4B36285C94F1C31F2041A406E90
- generatedChecksum: 5F23D19FF7A915FD35EAEBD1519599EF
  logicalPath: config\sam_c21n_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5F23D19FF7A915FD35EAEBD1519599EF
- generatedChecksum: 338F3F58BA5291CE0ADC155D2D1B0BA2
  logicalPath: config\sam_c21n_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 338F3F58BA5291CE0ADC155D2D1B0BA2
- generatedChecksum: 5A11AA1FDDF9F0E73B6C301368AC7CA3
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A11AA1FDDF9F0E73B6C301368AC7CA3
- generatedChecksum: 1FC17629B34A65B5263EB38F15B78374
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1FC17629B34A65B5263EB38F15B78374
- generatedChecksum: 85B1C6619285F00204D544FFB9488BD8
  logicalPath: packs\ATSAMC21N18A_DFP
  name: atsamc21n18a.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 85B1C6619285F00204D544FFB9488BD8
- generatedChecksum: 5E72410EBB7A36F4FCB4BEC646B6105B
  logicalPath: config\sam_c21n_xpro\bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E72410EBB7A36F4FCB4BEC646B6105B
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 5AAF3B829C83D883B06D3F334EEC9452
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: can.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5AAF3B829C83D883B06D3F334EEC9452
- generatedChecksum: B09070B7DD16FD62BDE35A43ED0ECF42
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ccl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B09070B7DD16FD62BDE35A43ED0ECF42
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 37B855C3B115037B7477C3B54FF5CEE7
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 37B855C3B115037B7477C3B54FF5CEE7
- generatedChecksum: F4F387BCCC1F1F523048623DCE6CB6E9
  logicalPath: config\sam_c21n_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F4F387BCCC1F1F523048623DCE6CB6E9
- generatedChecksum: ED54CC3C02BF37F9BB75C8C1EEB2BA77
  logicalPath: config\sam_c21n_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: ED54CC3C02BF37F9BB75C8C1EEB2BA77
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_c21n_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: AB529AAE2090CC7FE1A71093085CCFA2
  logicalPath: config\sam_c21n_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: AB529AAE2090CC7FE1A71093085CCFA2
- generatedChecksum: 00C5596E431499F03B918FEAE49A0DE6
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: divas.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 00C5596E431499F03B918FEAE49A0DE6
- generatedChecksum: 1E71642DD2ED9F76CF1DA2656A1D3912
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E71642DD2ED9F76CF1DA2656A1D3912
- generatedChecksum: 5B432D6C2727D42D994888527F582A0C
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5B432D6C2727D42D994888527F582A0C
- generatedChecksum: 13019E7960A453D60A452E9E9CFBF3B1
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 13019E7960A453D60A452E9E9CFBF3B1
- generatedChecksum: CF0980937FC04E0DAF71821DA38B0B89
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF0980937FC04E0DAF71821DA38B0B89
- generatedChecksum: 56ED9C4BB56E744FA794595A91E2C552
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: freqm.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 56ED9C4BB56E744FA794595A91E2C552
- generatedChecksum: C41B1C921B7B19E2391E3758EE67A074
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C41B1C921B7B19E2391E3758EE67A074
- generatedChecksum: B4D335F0A2FE10A54305E7D13944AEB5
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B4D335F0A2FE10A54305E7D13944AEB5
- generatedChecksum: 1DF1DD101F6D3E94C080A7192D393CC4
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: mclk.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1DF1DD101F6D3E94C080A7192D393CC4
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 1A444CD55FBEF78C4D86CA91488A1B2B
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1A444CD55FBEF78C4D86CA91488A1B2B
- generatedChecksum: F53BAA34BF2DC8BA0F5CABA5D1A6B4D0
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F53BAA34BF2DC8BA0F5CABA5D1A6B4D0
- generatedChecksum: AC130EB1BB50064A8D12794CA60F4A59
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: osc32kctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AC130EB1BB50064A8D12794CA60F4A59
- generatedChecksum: E1265F554F5D2EB503F06313F16AF175
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: oscctrl.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E1265F554F5D2EB503F06313F16AF175
- generatedChecksum: CF2972504591E8A971E6DB73EA09EA72
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF2972504591E8A971E6DB73EA09EA72
- generatedChecksum: 6726B0A73A60CCF6A766E658B965AEF7
  logicalPath: config\sam_c21n_xpro\peripheral\can
  name: plib_can0.h
  physicalPath: peripheral\can
  security: NON_SECURE
  type: HEADER
  userChecksum: 6726B0A73A60CCF6A766E658B965AEF7
- generatedChecksum: B09A4B5425BC469D730CCB20DC8B9AAF
  logicalPath: config\sam_c21n_xpro\peripheral\can
  name: plib_can_common.h
  physicalPath: peripheral\can
  security: NON_SECURE
  type: HEADER
  userChecksum: B09A4B5425BC469D730CCB20DC8B9AAF
- generatedChecksum: 0416F129713FDF989ACC1FC57065125C
  logicalPath: config\sam_c21n_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 0416F129713FDF989ACC1FC57065125C
- generatedChecksum: E209944E1E9ADE5142531BD2558D1923
  logicalPath: config\sam_c21n_xpro\peripheral\dsu
  name: plib_dsu.h
  physicalPath: peripheral\dsu
  security: NON_SECURE
  type: HEADER
  userChecksum: E209944E1E9ADE5142531BD2558D1923
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_c21n_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_c21n_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 3B509F96A28A3B2A3FDA7473BC7C6544
  logicalPath: config\sam_c21n_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 3B509F96A28A3B2A3FDA7473BC7C6544
- generatedChecksum: 2EEE78E89AA855B1C91A25E061E40C9F
  logicalPath: config\sam_c21n_xpro\peripheral\pac
  name: plib_pac.h
  physicalPath: peripheral\pac
  security: NON_SECURE
  type: HEADER
  userChecksum: 2EEE78E89AA855B1C91A25E061E40C9F
- generatedChecksum: 3F194CB1189A27167C7BE02C39CB257E
  logicalPath: config\sam_c21n_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F194CB1189A27167C7BE02C39CB257E
- generatedChecksum: 6BF0443303BC84911AA77A6DC63121FB
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6BF0443303BC84911AA77A6DC63121FB
- generatedChecksum: 204427AE87F9A3848BA68E545681A39E
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 204427AE87F9A3848BA68E545681A39E
- generatedChecksum: 45105DA01030929736A0619142433071
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 45105DA01030929736A0619142433071
- generatedChecksum: 0B036E93F3B47007B175F37B6AC43596
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0B036E93F3B47007B175F37B6AC43596
- generatedChecksum: 364F89B99F14F774964FEF4400F95231
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 364F89B99F14F774964FEF4400F95231
- generatedChecksum: FE2596FDA5D7CA449E5AB034DE301A2A
  logicalPath: packs\ATSAMC21N18A_DFP\pio
  name: samc21n18a.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: FE2596FDA5D7CA449E5AB034DE301A2A
- generatedChecksum: 3F53E80D3E935639E20475352E3E26DE
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: sdadc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F53E80D3E935639E20475352E3E26DE
- generatedChecksum: A29C76FBDF1228BA8621D402367CD15C
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A29C76FBDF1228BA8621D402367CD15C
- generatedChecksum: 2F2EF2FE010D71F9431397EBA3F56607
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2F2EF2FE010D71F9431397EBA3F56607
- generatedChecksum: 1C88891EA41DC4285FA93DA19923E555
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C88891EA41DC4285FA93DA19923E555
- generatedChecksum: 50CA1B3C5DE73CE17DB654CF9C38466E
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 50CA1B3C5DE73CE17DB654CF9C38466E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_c21n_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 5734F74138736E7EF09597F806F3CCD1
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: tsens.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5734F74138736E7EF09597F806F3CCD1
- generatedChecksum: 06B2955CF46E4039C745E91682394D29
  logicalPath: packs\ATSAMC21N18A_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMC21N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 06B2955CF46E4039C745E91682394D29
- generatedChecksum: 94108D65EAA0F3CD70DDC908D0FE51E8
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 94108D65EAA0F3CD70DDC908D0FE51E8
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_c21n_xpro;../src/packs/ATSAMC21N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32
  delimiter: ''
  key: place-data-into-section
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-startup-files
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_c21n_xpro;../src/packs/ATSAMC21N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
